[workspace]
members = ["verifier", "example/fibonacci-program", "example/script"]
resolver = "2"

[workspace.dependencies]
sp1-verifier = { version = "3.2.1", default-features = false }
sp1-sdk = { version = "3.2.1" }
sp1-zkvm = { version = "3.2.1" }
sp1-build = { version = "3.2.1" }
